name: audio
description: SoundCloud style audio player in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  built_collection: ^4.3.2
  built_value: ^7.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/waveforms/minikin_acid.json
    - assets/waveforms/minikin_past.json
    - assets/waveforms/minikin_background.json
    - assets/artworks/1.jpeg
    - assets/artworks/2.jpeg
    - assets/artworks/3.jpeg
