name: audio
description: SoundCloud style audio player in Flutter.

version: 0.0.1+1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.13.2
  built_collection: ^4.2.2
  built_value: ^6.8.2
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.0+3
  firebase_performance: ^0.3.1
  flutter_bloc: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^6.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
