name: audio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  built_collection: ^4.2.2
  built_value: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/waveforms/minikin_acid.json
    - assets/waveforms/minikin_past.json
