name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: subosito/flutter-action@v1
      with:
       channel: 'master'
    - name: Install dependencies
      run: flutter pub get
    - name: Analyzing project
      run: flutter analyze
